CREATE LOGIN BS WITH PASSWORD = '123';
CREATE LOGIN NV WITH PASSWORD = '123';
CREATE LOGIN AD WITH PASSWORD = '123';
CREATE LOGIN SY WITH PASSWORD = '123';
create LOGIN BN WITH PASSWORD = '123';
USE NhaKhoa
GO
CREATE USER userBN FOR LOGIN BN
CREATE USER userNV FOR LOGIN NV
CREATE USER userAD FOR LOGIN AD
CREATE USER userBS FOR LOGIN BS
CREATE USER userServer FOR LOGIN SY

EXEC SP_ADDROLE 'Ad'
EXEC SP_ADDROLE 'BenhNhan'
EXEC SP_ADDROLE 'NhanVien'
EXEC SP_ADDROLE 'BacSi'
EXEC SP_ADDROLE 'Sy'

EXEC sp_addrolemember 'Ad', 'userAD'
EXEC sp_addrolemember 'BenhNhan', 'userBN'
EXEC sp_addrolemember 'NhanVien', 'userNV'
EXEC sp_addrolemember 'BacSi', 'userBS'
EXEC sp_addrolemember 'Sy', 'userServer'

--Quyen AD 
-- Quyen quan li dich vu 

--------------------
USE NhaKhoa 
GO
GRANT EXECUTE ON SP_DANGNHAP TO Sy;
GRANT EXECUTE ON SP_XEMTOANBOTHUOC TO NhanVien;
GRANT EXECUTE ON SP_XEMTOANBOTHUOC TO BenhNhan; 
GRANT EXECUTE ON SP_XEMTOANBOTHUOC TO Ad;
GRANT EXECUTE ON SP_XEMTOANBOTHUOC TO BacSi; 

GRANT EXECUTE ON SP_XEMBENHAN TO BenhNhan; 
GRANT EXECUTE ON SP_XEMBENHAN TO BacSi;
GRANT EXECUTE ON SP_XEMBENHAN TO NhanVien; 
GRANT EXECUTE ON SP_XEMBENHAN TO Ad; 


GRANT EXECUTE ON SP_XEMTOANBODICHVU TO BenhNhan;
GRANT EXECUTE ON SP_XEMTOANBODICHVU TO BacSi;
GRANT EXECUTE ON SP_XEMTOANBODICHVU TO NhanVien; 
GRANT EXECUTE ON SP_XEMTOANBODICHVU TO Ad; 


GRANT EXECUTE ON SP_XEMTOANBOBACSI TO BacSi; 
GRANT EXECUTE ON SP_XEMTOANBOBACSI TO NhanVien;
GRANT EXECUTE ON SP_XEMTOANBOBACSI TO BenhNhan; 
GRANT EXECUTE ON SP_XEMTOANBOBACSI TO Ad; 

GRANT EXECUTE ON SP_xemtoanbonhanvien TO BacSi; 
GRANT EXECUTE ON SP_xemtoanbonhanvien TO NhanVien; 
GRANT EXECUTE ON SP_xemtoanbonhanvien TO BenhNhan; 
GRANT EXECUTE ON SP_xemtoanbonhanvien TO Ad; 

GRANT EXECUTE ON SP_xemtoanboadmin TO Ad; 
GRANT EXECUTE ON SP_xemtoanboadmin TO NhanVien; 
GRANT EXECUTE ON SP_xemtoanboadmin TO BacSi; 

GRANT EXECUTE ON SP_themdichvu TO Ad; 

GRANT EXECUTE ON SP_capnhatdichvu TO Ad; 

GRANT EXECUTE ON SP_THEMTAIKHOANBENHNHAN TO Ad; 
GRANT EXECUTE ON SP_THEMTAIKHOANBENHNHAN TO NhanVien; 

GRANT EXECUTE ON SP_XEMTHONGTINBENHNHAN TO BenhNhan; 
GRANT EXECUTE ON SP_XEMTHONGTINBENHNHAN TO NhanVien; 
GRANT EXECUTE ON SP_XEMTHONGTINBENHNHAN TO Ad; 
GRANT EXECUTE ON SP_XEMTHONGTINBENHNHAN TO BacSi; 

GRANT EXECUTE ON SP_THEMBENHAN TO BacSi; 
GRANT EXECUTE ON SP_THEMBENHAN TO Ad; 

GRANT EXECUTE ON SP_XEMBENHAN TO BenhNhan; 
GRANT EXECUTE ON SP_XEMBENHAN TO Ad; 
GRANT EXECUTE ON SP_XEMBENHAN TO NhanVien; 
GRANT EXECUTE ON SP_XEMBENHAN TO BacSi; 

GRANT EXECUTE ON SP_XOABENHAN TO BacSi; 
GRANT EXECUTE ON SP_XOABENHAN TO Ad; 
GRANT EXECUTE ON SP_XOABENHAN TO NhanVien; 

GRANT EXECUTE ON SP_XEMLICHHEN TO NhanVien; 
GRANT EXECUTE ON SP_XEMLICHHEN TO BacSi; 
GRANT EXECUTE ON SP_XEMLICHHEN TO Ad; 
GRANT EXECUTE ON SP_XEMLICHHEN TO BenhNhan; 








